import type { Metadata } from "next";
import "./globals.css";
import {
  Plus_Jakarta_Sans,
  Inter,
  Manrope,
  DM_Sans,
  Lexend,
} from "next/font/google";

const inter = Inter({ display: "swap", subsets: ["latin"] });
const plus = Plus_Jakarta_Sans({ display: "swap", subsets: ["latin"] });
const manrope = Manrope({ display: "swap", subsets: ["latin"] });
const dmSans = DM_Sans({ display: "swap", subsets: ["latin"] });
const lexend = Lexend({ display: "swap", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plus.className} antialiased`}>{children}</body>
    </html>
  );
}
